version: '2'
services:
  web:
    container_name: web-container
    build: ./web
    volumes:
      - ./web:/src/app
      - /src/app/node_modules
    ports:
     - "3030:3000"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
  db:
    container_name: db-container
    build: ./test-database
    ports:
    - "3306:3306"